apiVersion: v1
kind: Service
metadata:
  name: product-page
  labels:
    app: product-page
    service: product-page
spec:
  selector:
    app: product-page
  type: NodePort
  ports:
  - port: 9080
    name: http
    protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-page-v1
  labels:
    app: product-page
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-page
      version: v1
  template:
    metadata:
      labels:
        app: product-page
        version: v1
    spec:
      containers:
      - name: product-page
        image: rotchamar/g38:product-page-latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9080
        securityContext:
          runAsUser: 1000
---